# Generated by Django 4.2.5 on 2023-09-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_amount_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='skinType',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='*insert Steam trade link*'),
        ),
    ]
