# Generated by Django 4.2.5 on 2023-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_price_product_skintype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='tradeLink',
            field=models.TextField(default='-'),
        ),
    ]
