# Generated by Django 4.2.5 on 2023-09-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_description_product_tradelink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Pesanan',
        ),
    ]
