# Generated by Django 4.2.5 on 2023-09-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pesanan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='payment',
            field=models.TextField(default='-'),
        ),
    ]
