# Generated by Django 4.2.5 on 2023-09-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pesanan_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanan',
            name='tradeLink',
        ),
    ]
