# Generated by Django 4.2.5 on 2023-09-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_pesanan_tradelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='tradeLink',
            field=models.TextField(default='-'),
        ),
    ]
