# Generated by Django 4.2.5 on 2023-09-26 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pesanan_tradelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanan',
            name='tradeLink',
        ),
    ]
