# Generated by Django 4.2.5 on 2023-10-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_pesanan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
